POST http://localhost:8080/user/signin
Accept: application/json
Content-Type: application/json

{
  "email": "jor@gmail.com",
  "password": "12345"
}

###
POST http://localhost:8080/user
Accept: application/json
Content-Type: application/json

{
  "idUser": 3,
  "idPerson": 3,
  "name": "jorge",
  "firstSurname": "alejo",
  "secondSurname": "gutierrez",
  "phone": "75653453",
  "username": "jor123",
  "email": "jor@gmail.com",
  "password": "12345"
}

###
POST http://localhost:8080/user
Accept: application/json
Content-Type: application/json

{
  "idUser": 2,
  "idPerson": 2,
  "name": "Kevin",
  "firstSurname": "Escobar",
  "secondSurname": "Escobar",
  "phone": "72585398",
  "username": "kevin",
  "email": "escobarkev@gmail.com",
  "password": "12345"
}


###
PUT http://localhost:8080/user
Accept: application/json
Content-Type: application/json

{
  "idUser": 4,
  "idPerson": 4,
  "name": "erwin",
  "firstSurname": "alejo",
  "secondSurname": "gutierrez",
  "phone": "75653453",
  "username": "erwin123",
  "email": "erwin@gmail.com",
  "password": "12345"
}

###
DELETE http://localhost:8080/user?userId=1
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8080/user?userId=2
Accept: application/json
Content-Type: application/json
//Authorization: Bearer eyJpZFVzZXIiOjMsImlkU2VsbGVyIjozLCJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjIxMzYxMTY3LCJleHAiOjE2MjE0NDc1Njd9.vOXoVPZCvwbnAW8LahJSJtYUzf2f7SfDCNeK8JTxnKs8NHyyDos4AUWiF_1bUIouhDo9OMBkSUl4qqK111AHxg

###
GET http://localhost:8080/user/profile
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZFVzZXIiOjEwLCJpZFBlcnNvbiI6MTAsImFsZyI6IkhTNTEyIn0.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjM1OTk2MTY3LCJleHAiOjE2MzYwODI1Njd9.M-lvmkrjS7qQBaenQUgEw4yJ-wY9-HgAseC0JsE1rVVLthnw9cBbnkw7sf_6RlAAI5OZgQcWrCPdH0rZ9o0Rgg
